list=[1,2, 3]
print(list)
list.append(4)
print(list)
list.extend([5, 6, 7, 8, [9, 8]])
print(list)
list.extend([9 ,9])
print(list)
list.remove([9, 8])
print(list)
list.remove(9)
print(list)
list.remove(9)
print(list)